Sabat/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.urls import path, include

from Sabat import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('en/', include(('app_en.urls', 'app_en'), namespace='app_en')),
    path('', include(('app.urls', 'app'), namespace='app')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

app/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from Sabat import settings
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('city/<str:city>', views.city, name='city'),
    path('city/<str:city>/<str:village>', views.village, name='village'),

    path('donation', views.donation, name='donation'),
    path('aboutus', views.about_us, name='about_us'),
    path('visitingtimes', views.visiting_times, name='visiting_times'),
    path('membership', views.membership, name='membership'),
    path('museum', views.museum, name='museum'),
    path('market', views.market, name='market'),
    path('market/<str:type>', views.market_type, name='market_type'),
    path('gallery', views.gallery, name='gallery'),
    path('gallery/<int:id>', views.gallery_blog, name='gallery_blog'),
    path('oralhistory', views.oral_history, name='oral_history'),
    path('training', views.training, name='training'),
    path('training/<int:id>', views.training_blog, name='training_blog'),
    path('contactus', views.contact_us, name='contact_us'),
    path('processpayment/<str:d_id>/<str:amount>', views.process_payment, name='process_payment'),
    path('payment-done', views.payment_done, name='payment_done'),
    path('payment-cancelled', views.payment_canceled, name='payment_cancelled'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'

app_en/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from Sabat import settings
from app_en import views

app_name = 'app_en'

urlpatterns = [
    path('', views.index, name='index_en'),
    path('city/<str:city>', views.city, name='city_en'),
    path('city/<str:city>/<str:village>', views.village, name='village_en'),

    path('donation', views.donation, name='donation_en'),
    path('aboutus', views.about_us, name='about_us_en'),
    path('visitingtimes', views.visiting_times, name='visiting_times_en'),
    path('membership', views.membership, name='membership_en'),
    path('museum', views.museum, name='museum_en'),
    path('market', views.market, name='market_en'),
    path('market/<str:type>', views.market_type, name='market_type_en'),
    path('gallery', views.gallery, name='gallery_en'),
    path('gallery/<int:id>', views.gallery_blog, name='gallery_blog_en'),
    path('oralhistory', views.oral_history, name='oral_history_en'),
    path('training', views.training, name='training_en'),
    path('training/<int:id>', views.training_blog, name='training_blog_en'),
    path('contactus', views.contact_us, name='contact_us_en'),
    path('processpayment/<str:d_id>/<str:amount>', views.process_payment, name='process_payment_en'),
    path('payment-done', views.payment_done, name='payment_done_en'),
    path('payment-cancelled', views.payment_canceled, name='payment_cancelled_en'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
handler404 = 'app_en.views.handler404'
handler500 = 'app_en.views.handler500'

app/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from solo.models import SingletonModel


# Create your models here.
class Gallery(models.Model):
    title = models.CharField(max_length=255, verbose_name='العنوان')
    date = models.DateField(verbose_name='التاريخ')
    desc = models.TextField(verbose_name='النص')
    desc_en = models.TextField(verbose_name='النص english')
    image = models.ImageField(upload_to='images/gallery/')

    def __str__(self):
        return self.title


class Training(models.Model):
    title = models.CharField(max_length=255, verbose_name='العنوان')
    date = models.DateField(verbose_name='التاريخ')
    desc = models.TextField(verbose_name='النص')
    desc_en = models.TextField(verbose_name='النص english')
    image = models.ImageField(upload_to='images/training/')

    def __str__(self):
        return self.title


class AboutUs(SingletonModel):
    text = models.TextField()
    text_en = models.TextField()

    def __str__(self):
        return "About us - من نحن"


class City(models.Model):
    name = models.CharField(max_length=255, verbose_name='الأسم')
    name_en = models.CharField(max_length=255, verbose_name='الأسم انجليزي')

    def __str__(self):
        return self.name


class PanoramicPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='PanoramicPhotoCity')
    picture = models.ImageField(upload_to='./images/city/PanoramicPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class AerialPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="AerialPhotoCity")
    picture = models.ImageField(upload_to='images/city/AerialPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class ActionsPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="ActionsPhotoCity")
    picture = models.ImageField(upload_to='images/city/ActionsPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class EventsPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="EventsPhotoCity")
    picture = models.ImageField(upload_to='images/city/EventsPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class InstitutionPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="InstitutionPhotoCity")
    picture = models.ImageField(upload_to='images/city/InstitutionPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class CharactersPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="CharactersPhotoCity")
    picture = models.ImageField(upload_to='images/city/CharactersPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class MiscellaneousPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="MiscellaneousPhotoCity")
    picture = models.ImageField(upload_to='images/city/MiscellaneousPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class Village(models.Model):
    name = models.CharField(max_length=255, verbose_name='الأسم')
    name_en = models.CharField(max_length=255, verbose_name='الأسم انجليزي')
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='city', verbose_name='المدينة')
    des = models.TextField(verbose_name='description عربي')
    des_en = models.TextField(verbose_name='description english')

    def __str__(self):
        return "{} -> {}".format(self.city.name, self.name)


class PanoramicPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="PanoramicPhotoVillage")
    picture = models.ImageField(upload_to='./images/village/PanoramicPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class AerialPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="AerialPhotoVillage")
    picture = models.ImageField(upload_to='images/village/AerialPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class ActionsPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="ActionsPhotoVillage")
    picture = models.ImageField(upload_to='images/village/ActionsPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class EventsPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="EventsPhotoVillage")
    picture = models.ImageField(upload_to='images/village/EventsPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class InstitutionPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="InstitutionPhotoVillage")
    picture = models.ImageField(upload_to='images/village/InstitutionPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class CharactersPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="CharactersPhotoVillage")
    picture = models.ImageField(upload_to='images/village/CharactersPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class MiscellaneousPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="MiscellaneousPhotoVillage")
    picture = models.ImageField(upload_to='images/village/MiscellaneousPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class Donation(SingletonModel):
    text = models.TextField(verbose_name='النص')
    bank_info = models.TextField(verbose_name='معلوامات البنك')


class OralHistory(SingletonModel):
    text = models.TextField(verbose_name='النص')


class Embroidery(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/embroideries/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/book/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Herb(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/herb/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Olive(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/olive/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Accessories(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/accessories/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email


class DonationInfo(models.Model):
    d_id = models.AutoField(primary_key=True)
    amount = models.PositiveIntegerField(verbose_name="المبلغ")
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.d_id, self.amount)


class MuseumPhoto(models.Model):
    image = models.ImageField(upload_to='./images/Museum')

app_en/models.py
from django.db import models

# Create your models here.

app_en/templates/base_en.html
{% load static %}
{#{% load static %}#}
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sabbat</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:400,600,800">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
</head>
<body>
<!-- Nav Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid" style="background-color: black">
        <a class="navbar-brand" href="{% url 'app_en:index_en' %}">
            <img style="height: 120px ; width: 200px" src="{% static 'assets/img/newwhitelogo.png' %}" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="font-weight-bold nav-link"
                       href="{% url 'app_en:about_us_en' %}">
                        <p class="fw-bold">About Us</p></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:membership_en' %}"><p
                            class="fw-bold">Membership</p></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:donation_en' %}"><p
                            class="fw-bold">Donate</p></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:visiting_times_en' %}"><p
                            class="fw-bold">Visiting Times</p></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:museum_en' %}"><p
                            class="fw-bold">
                        The Museum</p></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:market_en' %}"><p
                            class="fw-bold">
                        Store</p></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:gallery_en' %}"><p
                            class="fw-bold">Gallery</p></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:oral_history_en' %}"><p
                            class="fw-bold">Oral History</p></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:training_en' %}"><p
                            class="fw-bold">Training</p></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_en:contact_us_en' %}"><p
                            class="fw-bold">Contact Us</p></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ request.path|slice:'3:' }}">
                        <p class="fw-bold">العربية</p>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>


<div class="container"
     style="margin-top: 1px;text-align: left;direction:ltr">

    {% block body_block %}

    {% endblock %}
</div>
<!-- Footer-->
<footer class="bg-light text-center text-white">
    <!-- Grid container -->
    <!--    <div class="container p-4 pb-0">-->
    <!--        &lt;!&ndash; Section: Social media &ndash;&gt;-->
    <!--        <section class="mb-4">-->
    <!--            &lt;!&ndash; Facebook &ndash;&gt;-->
    <!--            <a-->
    <!--                    class="btn btn-primary btn-floating m-1"-->
    <!--                    style="background-color: #3b5998;"-->
    <!--                    href="#"-->
    <!--                    role="button"-->
    <!--            ><i class="fab fa-facebook-f"></i-->
    <!--            ></a>-->


    <!--            &lt;!&ndash; Instagram &ndash;&gt;-->
    <!--            <a-->
    <!--                    class="btn btn-primary btn-floating m-1"-->
    <!--                    style="background-color: #ac2bac;"-->
    <!--                    href="#"-->
    <!--                    role="button"-->
    <!--            ><i class="fab fa-instagram"></i-->
    <!--            ></a>-->
    <!--        </section>-->
    <!--        &lt;!&ndash; Section: Social media &ndash;&gt;-->
    <!--    </div>-->
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: #212529">
        © 2022 Copyright:
        <a>Seif Farhan</a>
    </div>
    <!-- Copyright -->
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

<style>
    html, body {
        height: 100%;
    }

    .navbar-toggler-icon {
        background-color: white;
    }
    nav {
        text-align: center;
        font-size: medium;
        padding: 0;
        margin: 0;
    }


    nav li:hover {
        {#border-top: 4px solid white;#}
        {#border-bottom: 4px solid white;#}
        background-color: #0a53be;
        padding: 0;
    }

</style>

<script>
    let p_url = "enen"
</script>
</html>

app_en/templates/contact_us_en.html
{% extends 'base_en.html' %}

{% block body_block %}
    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="block-heading"><h2 class="text-info"
                                           style="color: #0dcaf0!important;margin-top: 20px;margin-bottom: 50px;">
                Contact us
            </h2>
                <p>Office phone:&nbsp;04.6020955<br><br>Personal phone: 050.3069125<br><br>Email<br>&nbsp;alsebat.2020@gmail.com<br><br>Facebook<br><br>Alsebat
                    Sebat<br><br>Museum Pages&nbsp;<br><br>
                    The Palestinian Heritage Museum- Nazareth
                    &nbsp;<br>Palestinian Archive 1948<br></p></div>
            <form action="" method="post">

                <div class="text mb-3">
                    {% csrf_token %}
                    <label class="form-label" for="id_subject">Subject</label>
                    <input class="form-control" type="text" id="id_subject" name="subject">
                </div>
                <div class="text mb-3">
                    {% csrf_token %}
                    <label class="form-label" for="id_email">Email</label>
                    <input class="form-control" type="email" id="id_email" name="email">
                </div>
                <div class="text mb-3">
                    {% csrf_token %}
                    <label class="form-label" for="id_message">Message</label>
                    <textarea class="form-control" id="id_message" name="message"></textarea>
                </div>
                <div class="text-center mb-3">
                    <input class="btn btn-primary" type="submit">
                </div>
            </form>
        </div>
    </section>

    <style>
        <!--
        .feature-box > p {
        --> <!-- font-family: 'Shilia W23';
        --> <!-- font-size: 1.1 em;
        --> <!-- font-weight: 15;
        --> <!-- line-height: 1.1 em;
        --> <!-- color: black;
        --> <!--
        }

        -->

        .block-heading > p {

            font-family: 'Shilia W23';
            font-size: 1.1em;
            font-weight: 15;
            line-height: 1.1em;
            color: black;
        }

        <!--
        .form-label {
        --> <!-- color: white;
        --> <!--
        }

        -->
        <!--
        .form-check-label {
        --> <!-- color: white;
        -->
        }
    </style>
{% endblock %}

app_en/templates/index_en.html
{% extends 'base_en.html' %}
{% load static %}

{% block body_block %}
<br>
<div class="row" style=" justify-content: center;background-color: black; margin-top: 80px;">
    <div class="col-md-10">
        <section
                style=" min-height: 300px ; background-color: black;"
                class="clean-block clean-hero"
        >
            <div class="text"><h2 style="font-family: 'Shilia W23';">Palestinian Refugees</h2>
                <p style="font-family: 'Shilia W23';">Are you displaced?</p><a class="btn btn-outline-light btn-lg ar-text-font" role="button" href="/contactus"
                                       data-bs-target="/contactus" style="font-family: 'Shilia W23';">Share your experience with us</a></div>
        </section>
    </div>
{#    <div class="col-md-5">#}
{#        <section class="clean-block clean-hero"#}
{#                 style=" min-height: 300px; background-color: black !important;">#}
{#            <div class="text ar-text-font"><h5 style="font-family: 'Shilia W23';">كل الشكر والتقدير</h5><h6 style="font-family: 'Shilia W23';">للسيد .....</h6>#}
{#                <p style="font-family: 'Shilia W23';">لمساهمته في دعم وتطوير المتحف والأرشيف&nbsp;<br></p></div>#}
{#        </section>#}
{#    </div>#}
</div>
<section style="background-color:transparent !important;" class="clean-block clean-info dark">
    <div class="container">
        <div class="row" style="margin-top: 30px;">
            <section class="d-flex align-content-start flex-wrap" style="margin-top: 20px;">
                <!--                    <div class="d-flex flex-row multiple-item-slider">-->
                {% for c in cities %}
                <div class="col-md-2">
                    <div class="justify-content-center spacer-slider">
                        <figure class="figure">
                            <img class="img-fluid figure-img"
                                 src="{{ 'media/images/cities/theimageback.jpeg' }}" alt="alt text here"
                                 style="opacity: 0.9">
                            <figcaption class="figure-caption"><h3 ><strong>{{ c.name_en }}</strong></h3>
                            </figcaption>
                            <a href="{% url 'app_en:city_en' c.name_en %}" class="stretched-link"></a>
                        </figure>
                    </div>
                </div>
                {% endfor %}
                <!--                    </div>-->
            </section>
        </div>
    </div>
</section>
<!--<section class="clean-block about-us">-->
<!--    <div class="container">-->
<!--        <div class="block-heading"><h2 style="color:black !important" class="text-info ar-text-font">اعضاء الجمعية</h2>-->
<!--            <p style="color:black !important">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in,-->
<!--                mattis vitae leo.</p></div>-->
<!--        <div style="margin-bottom: -100px;-->
<!--    background-color: black;" class="row justify-content-center">-->
<!--            <div class="col-sm-6 col-lg-4">-->
<!--                <div class="card text-center clean-card">-->
<!--                    <div style="background-color: black;" class="card-body info"><h4 style="color: white"  class="card-title">John Smith</h4>-->
<!--                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>-->
<!--                        <div class="icons"><a href="#"><i class="icon-social-facebook"></i></a><a href="#"><i-->
<!--                                class="icon-social-instagram"></i></a><a href="#"><i-->
<!--                                class="icon-social-twitter"></i></a></div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-sm-6 col-lg-4">-->
<!--                <div class="card text-center clean-card">-->
<!--                    <div style="background-color: black;" class="card-body info"><h4 style="color: white"  class="card-title">Robert Downturn</h4>-->
<!--                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>-->
<!--                        <div class="icons"><a href="#"><i class="icon-social-facebook"></i></a><a href="#"><i-->
<!--                                class="icon-social-instagram"></i></a><a href="#"><i-->
<!--                                class="icon-social-twitter"></i></a></div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-sm-6 col-lg-4">-->
<!--                <div class="card text-center clean-card">-->
<!--                    <div style="background-color: black;" class="card-body info"><h4 style="color: white" class="card-title">Ally Sanders</h4>-->
<!--                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>-->
<!--                        <div class="icons"><a href="#"><i class="icon-social-facebook"></i></a><a href="#"><i-->
<!--                                class="icon-social-instagram"></i></a><a href="#"><i-->
<!--                                class="icon-social-twitter"></i></a></div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</section>-->

<style>
    .clean-block.clean-hero:before {
    background-color: transparent !important;
}
    .text-info {
    background-color: transparent !important;
}
        img {
            width: 500px;
            height: 550px;
        }

        figure figcaption {
            text-align: center;
            margin-bottom: 50%;
        }

        body {
            background: #b4a890;
        }


</style>
{% endblock %}


<!--        background-image: url({% static 'assets/img/backgroundImg.jpg' %});-->
<!--        background-repeat: no-repeat;-->
<!--        background-attachment: fixed;-->
<!--        background-size: 100% 100%;-->

app_en/templates/payment_cancelled_en.html
{% extends 'base_en.html' %}

{% block content %}

    <p>Payment cancelled.</p>

{% endblock %}

app_en/templates/payment_done_en.html
{% extends 'base_en.html' %}

{% block body_block %}

    <p>Payment done.</p>

{% endblock %}