Sabat/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.urls import path, include

from Sabat import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('en/', include(('app_en.urls', 'app_en'), namespace='app_en')),
    path('', include(('app.urls', 'app'), namespace='app')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

app/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from Sabat import settings
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('city/<str:city>', views.city, name='city'),
    path('city/<str:city>/<str:village>', views.village, name='village'),

    path('donation', views.donation, name='donation'),
    path('aboutus', views.about_us, name='about_us'),
    path('visitingtimes', views.visiting_times, name='visiting_times'),
    path('membership', views.membership, name='membership'),
    path('museum', views.museum, name='museum'),
    path('market', views.market, name='market'),
    path('market/<str:type>', views.market_type, name='market_type'),
    path('gallery', views.gallery, name='gallery'),
    path('gallery/<int:id>', views.gallery_blog, name='gallery_blog'),
    path('oralhistory', views.oral_history, name='oral_history'),
    path('training', views.training, name='training'),
    path('training/<int:id>', views.training_blog, name='training_blog'),
    path('contactus', views.contact_us, name='contact_us'),
    path('processpayment/<str:d_id>/<str:amount>', views.process_payment, name='process_payment'),
    path('payment-done', views.payment_done, name='payment_done'),
    path('payment-cancelled', views.payment_canceled, name='payment_cancelled'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'

app/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from solo.models import SingletonModel


# Create your models here.
class Gallery(models.Model):
    title = models.CharField(max_length=255, verbose_name='العنوان')
    date = models.DateField(verbose_name='التاريخ')
    desc = models.TextField(verbose_name='النص')
    desc_en = models.TextField(verbose_name='النص english')
    image = models.ImageField(upload_to='images/gallery/')

    def __str__(self):
        return self.title


class Training(models.Model):
    title = models.CharField(max_length=255, verbose_name='العنوان')
    date = models.DateField(verbose_name='التاريخ')
    desc = models.TextField(verbose_name='النص')
    desc_en = models.TextField(verbose_name='النص english')
    image = models.ImageField(upload_to='images/training/')

    def __str__(self):
        return self.title


class AboutUs(SingletonModel):
    text = models.TextField()
    text_en = models.TextField()

    def __str__(self):
        return "About us - من نحن"


class City(models.Model):
    name = models.CharField(max_length=255, verbose_name='الأسم')
    name_en = models.CharField(max_length=255, verbose_name='الأسم انجليزي')

    def __str__(self):
        return self.name


class PanoramicPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='PanoramicPhotoCity')
    picture = models.ImageField(upload_to='./images/city/PanoramicPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class AerialPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="AerialPhotoCity")
    picture = models.ImageField(upload_to='images/city/AerialPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class ActionsPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="ActionsPhotoCity")
    picture = models.ImageField(upload_to='images/city/ActionsPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class EventsPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="EventsPhotoCity")
    picture = models.ImageField(upload_to='images/city/EventsPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class InstitutionPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="InstitutionPhotoCity")
    picture = models.ImageField(upload_to='images/city/InstitutionPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class CharactersPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="CharactersPhotoCity")
    picture = models.ImageField(upload_to='images/city/CharactersPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class MiscellaneousPhotoCity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="MiscellaneousPhotoCity")
    picture = models.ImageField(upload_to='images/city/MiscellaneousPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class Village(models.Model):
    name = models.CharField(max_length=255, verbose_name='الأسم')
    name_en = models.CharField(max_length=255, verbose_name='الأسم انجليزي')
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='city', verbose_name='المدينة')
    des = models.TextField(verbose_name='description عربي')
    des_en = models.TextField(verbose_name='description english')

    def __str__(self):
        return "{} -> {}".format(self.city.name, self.name)


class PanoramicPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="PanoramicPhotoVillage")
    picture = models.ImageField(upload_to='./images/village/PanoramicPhotoCity')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class AerialPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="AerialPhotoVillage")
    picture = models.ImageField(upload_to='images/village/AerialPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class ActionsPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="ActionsPhotoVillage")
    picture = models.ImageField(upload_to='images/village/ActionsPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class EventsPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="EventsPhotoVillage")
    picture = models.ImageField(upload_to='images/village/EventsPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class InstitutionPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="InstitutionPhotoVillage")
    picture = models.ImageField(upload_to='images/village/InstitutionPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class CharactersPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="CharactersPhotoVillage")
    picture = models.ImageField(upload_to='images/village/CharactersPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class MiscellaneousPhotoVillage(models.Model):
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name="MiscellaneousPhotoVillage")
    picture = models.ImageField(upload_to='images/village/MiscellaneousPhotoVillage')
    caption = models.CharField(max_length=255, verbose_name='caption عربي')
    caption_en = models.CharField(max_length=255, verbose_name='caption english')


class Donation(SingletonModel):
    text = models.TextField(verbose_name='النص')
    bank_info = models.TextField(verbose_name='معلوامات البنك')


class OralHistory(SingletonModel):
    text = models.TextField(verbose_name='النص')


class Embroidery(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/embroideries/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/book/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Herb(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/herb/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Olive(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/olive/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Accessories(models.Model):
    name = models.CharField(max_length=255, verbose_name='الاسم')
    image = models.ImageField(upload_to='images/accessories/', verbose_name='الصورة')
    description = models.TextField(verbose_name='النص')
    description_en = models.TextField(verbose_name='النص english')
    price = models.PositiveIntegerField(verbose_name='السعر')

    def __str__(self):
        return self.name


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email


class DonationInfo(models.Model):
    d_id = models.AutoField(primary_key=True)
    amount = models.PositiveIntegerField(verbose_name="المبلغ")
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.d_id, self.amount)


class MuseumPhoto(models.Model):
    image = models.ImageField(upload_to='./images/Museum')

app/templates/about_us.html
{% extends 'base.html' %}

{% block body_block %}
<!--<p>-->
<!--    {{ text.upper }}-->
<!--</p>-->
<div class="container">
    <div class="row">
        <div class="col-4 d-sm-none d-md-block " style="margin-top: 150px;">
            <div class="embed-responsive hidden-phone embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/g1Qom1J2nK8" frameborder="0" allowfullscreen ng-show
                        allowfullscreen></iframe>
            </div>
            <div class="embed-responsive embed-responsive-16by9" style="margin-top: 100px;">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/aVIGPFf8sOM"
                        allowfullscreen></iframe>
            </div>
            <div class="embed-responsive embed-responsive-16by9" style="margin-top: 100px;">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/_PQ4ES9QlXI"
                        allowfullscreen></iframe>
            </div>
            <div class="embed-responsive embed-responsive-16by9" style="margin-top: 100px;">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/rkvEkWOWmQw"
                        allowfullscreen></iframe>
            </div>
        </div>
        <div class="col-8 block-heading"><h2 class="text-info"
                                              style="color: #0dcaf0!important;margin-top: 20px;margin-bottom: 20px;">من
            نحن</h2>
            {% for t in text %}
                <p class="d-line">{{ t }}</p>
            {% endfor %}
{#            <p class="d-inline">{{ text }}</p>#}
{#            <h1>&nbsp;</h1><h4>جمعية السباط للحفاظ على الثقافة والتراث (ج.م.) – تأسست عام 1999م</h4><h5>&nbsp;</h5>#}
{#            <p class="d-inline">منذ سنوات تعمل جمعية السباط للحفاظ على التراث (موقعها مدينة الناصرة) في بيت من بيوت#}
{#                الناصرة التقليدية (يشمل البيت ستة غرف (عقد)، مغارة داخلية، و حاكورة مسجلة بالطابو العثماني) التي#}
{#                بنيت أواخر القرن التاسع عشر، ويعود بملكيته لعائلة نصراوية عريقة</p><h5>&nbsp;</h5>#}
{#            <p class="d-table-row">قبل سنوات نجحت جمعية السباط للحفاظ على التراث الفلسطيني في استئجار البيت وتحويله#}
{#                إلى متحف للتراث الفلسطيني وذلك كجزء من الحفاظ على الهوية الفلسطينية وعلى موروثنا&nbsp; &nbsp;التاريخي#}
{#                والحضاري والتراثي. حيث وضعت الجمعية نصب أعينها عدة أهداف لمشاريعها كان أهمها</p><h5>&nbsp;</h5>#}
{#            <p>متحف التراث ، (بيت التراث الشعبي). تأسس عام 1999م</p><h5>&nbsp;</h5>#}
{#            <p style="/*margin: 0 0 10px;*/unicode-bidi: bidi-override;direction: rtl;">محتويات#}
{#                المتحف:<br><br><br><br>في ثنايا المتحف مجموعة كبيرة من الأدوات التراثية التي استخدمها الإنسان#}
{#                الفلسطيني الذي يعيش في بلد عاشت فيها أقدم الحضارات، ونشأت فيها الديانات السماوية الثلاث. يمكننا#}
{#                تصنيفها حسب حقبها التاريخية إلى مجموعات :<br><br><br><br>1- المجموعة الأثرية ، وتحوي جرة وبعض الصحون#}
{#                الكنعانية ، قوارير و "ساركوفاج" – تابوت حجري روماني وبعض الحجارة الأثرية .<br><br>2- مجموعة أواني#}
{#                للزينة ، تعود للفترة المملوكية ، 0521-6151.<br><br>3- مجموعة من الأواني والأدوات والأسلحة التقليدية#}
{#                تعود للفترة العثمانية ، 6151- 6191.<br><br>4- مجموعة من الأدوات التراثية الفلسطينية ابان الانتداب#}
{#                البريطاني . نذكر أهمها :<br><br>2- أدوات العمل .<br><br>3- أدوات المطبخ .<br><br>4- الزي الشعبي#}
{#                التقليدي للنساء والرجال.<br><br>5-الإكسسوارات، الحلي والزينة.<br><br>6- ادوات الانارة والطهي#}
{#                .<br><br>7- معروضات البيت العربي .<br><br>8- الصيدلية التقليدية – الأكزاخانه. ومجموعة من السجلات#}
{#                والكتب الطبية والرسومات التي يظهر فيها تاريخ الطب القديم وحتى يومنا هذا.<br><br>باختصار يحوي المتحف#}
{#                مجموعة كبيرة من المعروضات تصل إلى أكثر من 007 قطعة ، تحاكي واقعنا الفلسطيني قبل النكبة.<br><br></p>#}
        </div>
    </div>
</div>

<style>

    .block-heading > p {
    font-family: 'Shilia W23';
     font-size: 1.1em;
     font-weight: 15;
     line-height: 1.1em;
    color: black;
    }

    @media screen and (max-width: 576px) and (min-width: 0px) {
  .desktop-only {
    display: none !important;
}





</style>

{% endblock %}

app/templates/base.html
{% load static %}
{#{% load static %}#}
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="UTF-8">
    <title>جمعية السباط</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:400,600,800">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
</head>
<body>
<!-- Nav Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div style="background-color: black;" class="container-fluid">
        <a class="navbar-brand" href="{% url 'app:index' %}">
            <img style="height: 120px ; width: 200px" src="{% static 'assets/img/newwhitelogo.png' %}" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="font-weight-bold nav-link" href="{% url 'app:about_us' %}">
                        <p class="fw-bold">من نحن</p></a></button>
                </li>
                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:membership' %}"><p
                            class="fw-bold">سجل العضوية</p></a></button>
                </li>
                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:donation' %}"><p
                            class="fw-bold">تبرع</p></a></button>
                </li>

                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:visiting_times' %}"><p
                            class="fw-bold">أوقات الزيارة</p></a></button>
                </li>

                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:museum' %}"><p class="fw-bold">
                        المتحف</p></a></button>
                </li>

                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:market' %}"><p class="fw-bold">
                        دكان</p></a></button>
                </li>

                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:gallery' %}"><p
                            class="fw-bold"> معارض Gallery</p></a></button>
                </li>
                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:oral_history' %}"><p
                            class="fw-bold">التاريخ الشفوي</p></a></button>
                </li>
                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:training' %}"><p
                            class="fw-bold">دورات</p></a></button>
                </li>
                <li class="nav-item">
                    <button class="navbar-btn btn"><a class="nav-link" href="{% url 'app:contact_us' %}"><p
                            class="fw-bold"> اتصلوا بنا</p></a></button>
                </li>

                <li class="nav-item">
                    <button class="navbar-btn btn">
                        <a class="nav-link"
                           href="{% url 'app:index' %}{{ current_path }}">
                            <p class="fw-bold">English</p>
                        </a>
                    </button>
                </li>

            </ul>
        </div>
    </div>
</nav>


<div class="container"
     style="margin-top: 1px;text-align: right;direction:rtl">

    {% block body_block %}

    {% endblock %}
</div>
<!-- Footer-->
<footer class="bg-light text-center text-white">
    <!-- Grid container -->
    <!--    <div class="container p-4 pb-0">-->
    <!--        &lt;!&ndash; Section: Social media &ndash;&gt;-->
    <!--        <section class="mb-4">-->
    <!--            &lt;!&ndash; Facebook &ndash;&gt;-->
    <!--            <a-->
    <!--                    class="btn btn-primary btn-floating m-1"-->
    <!--                    style="background-color: #3b5998;"-->
    <!--                    href="#"-->
    <!--                    role="button"-->
    <!--            ><i class="fab fa-facebook-f"></i-->
    <!--            ></a>-->


    <!--            &lt;!&ndash; Instagram &ndash;&gt;-->
    <!--            <a-->
    <!--                    class="btn btn-primary btn-floating m-1"-->
    <!--                    style="background-color: #ac2bac;"-->
    <!--                    href="#"-->
    <!--                    role="button"-->
    <!--            ><i class="fab fa-instagram"></i-->
    <!--            ></a>-->
    <!--        </section>-->
    <!--        &lt;!&ndash; Section: Social media &ndash;&gt;-->
    <!--    </div>-->
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: #212529">
        © 2022 Copyright:
        <a>Seif Farhan</a>
    </div>
    <!-- Copyright -->
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

<style>
    html, body {
        height: 100%;
    }

    .navbar-toggler-icon {
        background-color: white;
    }


</style>

</html>

app/templates/contact_us.html
{% extends 'base.html' %}

{% block body_block %}
    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="block-heading"><h2 class="text-info"
                                           style="color: #0dcaf0!important;margin-top: 20px;margin-bottom: 50px;">اتصلوا
                بنا</h2>
                <p>رقم المكتب:&nbsp;04.6020955<br><br>رقم شخصي: 050.3069125<br><br>البريد الالكتروني<br>&nbsp;alsebat.2020@gmail.com<br><br>حساب
                    الفيسبوك<br><br>Alsebat Sebat<br><br>صفحات المتحف&nbsp;<br><br>متحف التراث الفلسطيني-
                    الناصرة&nbsp;<br>الارشيف الفلسطيني 1948&nbsp;<br></p></div>
            <form action="" method="post">
                {#                <input type="hidden" name="csrfmiddlewaretoken"#}
                {#                       value="yTF5g7ceTgkwsOimKxZpuV10DG4a1TWFwQ60pneu047lPvu6kTAlNYPfYEC9G8jq">#}
                {#                <div class="text-end mb-3">#}
                {#                    <label class="form-label text-end" for="name">الاسم</label>#}
                {#                    <input class="form-control" type="text" id="name" name="name">#}
                {#                </div>#}
                <div class="text-end mb-3">
                    {% csrf_token %}
                    <label class="form-label" for="id_subject">الموضوع</label>
                    <input class="form-control" type="text" id="id_subject" name="subject">
                </div>
                <div class="text-end mb-3">
                    {% csrf_token %}
                    <label class="form-label" for="id_email">الأيميل</label>
                    <input class="form-control" type="email" id="id_email" name="email">
                </div>
                <div class="text-end mb-3">
                    {% csrf_token %}
                    <label class="form-label" for="id_message">الرسالة</label>
                    <textarea class="form-control" id="id_message" name="message"></textarea>
                </div>
                <div class="text-center mb-3">
                    <input class="btn btn-primary" type="submit">
                </div>
            </form>
        </div>
    </section>

<style>
<!--        .feature-box > p {-->
<!--    font-family: 'Shilia W23';-->
<!--     font-size: 1.1em;-->
<!--     font-weight: 15;-->
<!--     line-height: 1.1em;-->
<!--    color: black;-->
<!--    }-->

        .block-heading > p {

    font-family: 'Shilia W23';
     font-size: 1.1em;
     font-weight: 15;
     line-height: 1.1em;
    color: black;
    }
<!--        .form-label {-->
<!--    color : white ;-->
<!--    }-->
<!--        .form-check-label {-->
<!--    color : white ;-->
    }
</style>
{% endblock %}

app/templates/gallery.html
{% extends 'base.html' %}

{% block body_block %}
    <section class="clean-block clean-blog-list dark">
        <div class="container">
            <div class="block-heading"><h2 class="text-info"
                                           style="color: #0dcaf0!important;margin-top: 20px;margin-bottom: 50px;">
                المعرض</h2>
                <p style="margin-bottom: 50px;">هنا يتم عرض كل النشاطات&nbsp;</p></div>
            <div class="block-content">

                {% for g in gallery %}
                    <div class="clean-blog-post">
                        <div class="row">
                            <div class="col-lg-5"><img class="rounded img-fluid"
                                                       src="{{ g.image.url }}" alt="">
                            </div>
                            <div class="col-lg-7"><h3>{{ g.title }}</h3>
                                <div class="info"><span class="text-muted">{{ g.date | date }}</span></div>
                                <p class="text">
                                    {{ g.desc }}
                                </p>
                                <a class="btn btn-outline-primary btn-sm" role="button"
                                   href="{% url 'app:gallery_blog' g.pk %}">المزيد </a></div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>
    </section>

    <style>
        .text {
            display: block;
            width: 100px;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
        }


    .block-heading > p {
    font-family: 'Shilia W23';
     font-size: 1.1em;
     font-weight: 15;
     line-height: 1.1em;
    color: black;
    }




    </style>
{% endblock %}